[package]
name = "recursive_tic_tac"
version = "0.1.0"
authors = ["ganidhu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
